title: "Willard Robinson"
description: "Willard Robinson, environmental economist and Ph.D. candidate at NC State University."
url: "https://wmrobin.github.io"
author: 
  name: Willard Robinson
  twitter: WMRobinEcon
  googlescholar: https://scholar.google.com/citations?hl=en&user=N2DAyCQAAAAJ
defaults:
    - scope:
        path: ""
      values:
        image: /images/WillRobinson.jpg
destination: docs
keep_files: [".nojekyll"]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: WMRobinEcon
  card: summary

social:
  name: Willard Robinson
  links:
    - https://twitter.com/WMRobinEcon
    - https://github.com/WMRobin

webmaster_verifications:
  google: apxfYeosxqOM5sqd5ri-fn1RF0FpUE1oWwMbxMH9Rkg

exclude:
  - docs/
  - "*.Rmd"
  - _site.yml
  - Gemfile
  - Gemfile.lock
  - "*.Rproj"
  - header.html
  - style.css
  - rank-counts.csv
  - jobmarket/
  - "*.tex"
  - "*.aux"
  - "*.log"
  - "*.out"
  - "*.fls"
  - "*.fdb_latexmk"
  - "*.synctex.gz"

nav_left:
  - text: "Home"
    href: "/"
    icon: "fa-mountain-sun"
  - text: "Research"
    href: "/research"
    icon: "fa-pen"
  - text: "CV"
    href: "/cv"
    icon: "fa-file"
  # - text: "Public goods"
  #   href: "/public-goods"
  #   icon: "fa-code"

nav_right:
  - icon: "fa-solid fa-envelope"
    href: "mailto:wmrobin3@ncsu.edu"
    label: "Email"
  # - icon: "fa-brands fa-x-twitter"
  #   href: "https://twitter.com/WMRobinEcon"
  #   label: "Twitter"
  - icon: "fa-brands fa-github"
    href: "https://github.com/WMRobin"
    label: "GitHub"
  - icon: "fab fa-google-scholar"
    href: "https://scholar.google.com/citations?hl=en&user=N2DAyCQAAAAJ"
    label: "Google Scholar"
  - icon: "fab fa-orcid"
    href: "https://orcid.org/0009-0003-1770-6114"
    label: "ORCID profile"