---
title: "CV"
pagetitle: "CV | Willard Robinson"
---

<style>
  .section h2,
  .section h3,
  .section h4,
  .section h5,
  .section h6 {
    color: #604479;
  }

  .section h2 {
    margin-bottom: -2.5px;
  }

  .section h3 {
    margin-bottom: -5px;
  }

  p,
  ul,
  li {
    font-size: 18px;
      color: #2f4858;
  }

  a {
        color: #dd3414;
        font-weight: 500;
    }
</style>

Click <a href="cv/robinson-cv.pdf" target="_blank">here</a> for PDF version.

## Education

**Ph.D. Economics**, North Carolina State University, 2027 (expected)

**M.S. Applied Economics**, Montana State University, 2022

**B.A. Economics** (Mathematics minor, *summa cum laude*), Appalachian State University, 2020

## Teaching experience
<font size="3">(*U.* = Undergraduate course *Ph.D.* = Doctorate course)</font>

### Instructor
* **ARE 336** (*U.*): Introduction to Environmental and Resource Economics (NCSU)
  * Fall 2025
* **ECNS 202** (*U.*): Principles of Macroeconomics (MSU)
  * Fall 2021, Spring 2022

### Graduate teaching assistant
* **ECG 715** (*Ph.D.*): Environmental and Resource Economics I (NCSU)
  * Fall 2024
* **ECG 702** (*Ph.D.*): Microeconomic Theory II (NCSU)
  * Spring 2024
* **ARE 336** (*U.*): Environmental and Resource Economics (NCSU)
  * Fall 2023, Spring 2025
* **EC 201** (*U.*): Principles of Microeconomics (NCSU)
  * Fall 2022, Spring 2023, Fall 2023
* **ECNS 202** (*U.*): Principles of Macroeconomics (MSU)
  * Summer 2021, Summer 2022

## Research experience

* <a href="https://cenrep.ncsu.edu/" target="_blank">CEnREP</a> graduate student affilitate: Jun. 2023 to present
* Research assistant with <a href="https://spencerbanzhaf.wordpress.ncsu.edu/" target="_blank">Spencer Banzhaf</a>: Jan. 2024 through May 2025
* Graduate Fellow at the <a href="https://perc.org/" target="_blank">Property and Environment Research Center</a>: Summer 2025
* Research assistant with <a href="https://sites.google.com/site/umutdur/" target="_blank">Umut Dur</a>: Jan. 2025 to present
* Research assistant with <a href="https://www.nickhagerty.com/" target="_blank">Nick Hagerty</a>: Aug. 2020 through May 2022
