---
title: "Serial dictator program (Julia)"
editor_options: 
  markdown: 
    wrap: sentence
---
<style>
table {
  table-layout: auto;
  width: auto;
  border-collapse: collapse;
}
th, td {
  border: 1px solid black;
  padding: 8px;
}
</style>

I wrote this program to help with assigning papers to reviewers for a peer review group I helped start.

The program is written in the wonderful <a href="https://julialang.org/" target="_blank">Julia</a> language, but I will happily translate it to other languages (most easily in R or Stata) if there is a demand!

The
<a href="https://people.duke.edu/~aa88/articles/rsrcECMA.pdf" target="_blank">serial dictator</a>
mechanism is used to fairly assign each reviewer a paper to review.
The reviewers are given a list of papers, and they submit a rank ordered list.
These lists are then fed into the mechanism and a fair allocation is output!

### How the serial dictator works: an example

To illustrate, assume there are three papers to be assigned $\{a,b,c\}$ and three potential reviewers $\{1,2,3\}$.
Reviewer $i$'s preferences are denoted by $P_i$.
For this example, I'll use the following preferences:

$$
\begin{array}{ccc}
  P_1 & P_2 & P_3 \\ \hline
  a & a & b \\
  b & c & a \\
  c & b & c
\end{array}
$$

To get the best possible allocation, the allocator wants to consider consider all possible orders of dictatorship.
With three potential reviewers, these are:

$$
\begin{array}{rl}
  \text{order 1}: & 1 \to 2 \to 3 \\
  \text{order 2}: & 1 \to 3 \to 2 \\
  \text{order 3}: & 2 \to 1 \to 3 \\
  \text{order 4}: & 2 \to 3 \to 1 \\
  \text{order 5}: & 3 \to 1 \to 2 \\
  \text{order 6}: & 3 \to 2 \to 1
\end{array}
$$


The allocation of dictator order $k$ for individual $i$ is denoted $\mu_k(i)$.

I'll illustrate with order 1.
The mechanism works according to the following steps:

0.  Define the set of available objects as $A_1 = \{1,2,3\}$
0.  Person 1 chooses first. All objects are in the available set, so she gets her most preferred item. So, $\mu_1(1) = a$. Update the set of available objects to be $A_2 = A_1 \setminus \{\mu_1(1)\}$.
0.  Person 2 chooses her most preferred item from $A_2$. Her most preferred item is not available, so she gets her second-most preferred item. So, $\mu_1(2) = c$. Update the set of available objects to be $A_3 = A_2 \setminus \{\mu_1(1), \mu_1(2)\}$.
0.  There is only one item in the available set, so the third person is assigned that item. So $\mu_1(3) = b$. (her most preferred!)

The final allocation for dictator order 1 is $\mu_1 = (a,c,b)$.

How well off are the people under this allocation?
A simple way to calculate an individual's welfare is to subtract 4 (the number of objects + 1) from the ranking of their allocation.
We'll call this the "payoff" to the individual.

Let $P_i(\mu_1)$ be the ranking of person $i$'s allocated object; their payoff is then $4 - P_i(\mu_1)$.
The total welfare of the allocation for serial dictator order $k$ is
$$V_k = \sum_{i=1}^3 \left(4 - P_i(\mu_k)\right).$$
This means order 1 has a payoff of 5.

### How you can use this program

The program goes through all permutations of dictatorship orders to find the one that maximizes payoff defined in this way.
Note that the program can handle a larger number of individuals than objects, but it cannot allocate more objects than there are people.
This is mainly because everybody who submitted a paper for review was required to be a reviewer, so there was by design always at least as many reviewers as there were papers.

I find it interesting to see how "popular" the papers were, so the program saves a histogram table as a CSV.
This table is called <code>rank-counts.csv</code>.
The main allocation is saved in <code>serial-dictator-allocation.csv</code> and can be easily opened in Excel or Google Sheets.

You will need to provide three parameters at the start of the program: <code>indir</code>, <code>outdir</code>, and <code>filename</code>. These are, respectively, the directory containing your preferences CSV, the directory where you would like the allocation saved, and the name of the CSV containing your preferences.
Update these parameters and you're good to go!

### Program download (and sample data)

<a href="public-goods/serial-dictator-program/serial-dictator-program.jl" target="_blank">Download the program here</a> and use this <a href="public-goods/serial-dictator-program/example-preferences.csv" target="_blank">example data</a> to see how it works!

Note that to use it, you should upload a CSV with column names that are the names of individuals and their preferences descending in favorability.
For example, the data for a 4-person, 3-object setting should look like the table below:

<div style="display: flex; justify-content: center;" width="100%">
  <table>
    <thead>
      <tr>
        <th>Adam</th>
        <th>Bob</th>
        <th>Candace</th>
        <th>David</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Adam's first choice</td>
        <td>Bob's first choice</td>
        <td>Candace's first choice</td>
        <td>David's first choice</td>
      </tr>
      <tr>
        <td>Adam's second choice</td>
        <td>Bob's second choice</td>
        <td>Candace's second choice</td>
        <td>David's second choice</td>
      </tr>
      <tr>
        <td>Adam's third choice</td>
        <td>Bob's third choice</td>
        <td>Candace's third choice</td>
        <td>David's third choice</td>
      </tr>
    </tbody>
  </table>
</div>